services:
  haskmc:
    # Make sure to change the tag to the haskmc version you want to use.
    # https://github.com/haskbasirat/HaskMC/pkgs/container/haskmc/versions?filters%5Bversion_type%5D=tagged
    #image: ghcr.io/haskbasirat/haskmc:main
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./data:/haskmc
      # Use the following, if you want to make your config immutable
      #- ./config:/haskmc/config:ro
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    stdin_open: true
    tty: true
    cap_drop:
      - ALL
    read_only: true
